import React from 'react'
import Navbar from '../componenets/Navbar'

export default function Home() {
  return (
    <div>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio laborum perspiciatis dolor, nesciunt iure quod fuga maiores cumque fugit, molestias odio et eligendi! Quasi enim corporis ipsam quia dolorem ipsum tenetur blanditiis quaerat tempore! Similique unde optio ratione illo beatae maiores doloribus animi praesentium quae, rerum accusamus ipsum, laborum, omnis quam. Ea id veritatis blanditiis! Dolorem odio ad ipsam error iusto possimus consequuntur vero est, nobis itaque ullam a nostrum alias. Deserunt explicabo non, ab corrupti numquam adipisci ducimus mollitia placeat necessitatibus rerum quis amet quo tenetur molestias recusandae quas. Adipisci vitae nihil voluptates, nulla, tempora aliquam fuga fugit nam aperiam voluptatibus sunt illum dolorum ullam enim odio quia labore animi maxime libero amet eligendi. Dolorum, quis nihil quos, in debitis beatae temporibus ut laborum dicta veritatis earum eveniet error voluptatem hic alias officia odit facere non possimus, voluptas voluptate quae! Id optio repellat voluptas, harum, facere autem saepe porro hic reprehenderit voluptatem velit magnam atque fuga eveniet quisquam est facilis architecto accusantium perferendis accusamus eaque assumenda, quaerat neque! Necessitatibus corporis impedit tenetur magnam hic, assumenda blanditiis aliquam, distinctio quam doloribus labore iusto temporibus tempore iste architecto eaque culpa nam nesciunt natus aspernatur dolorem numquam facilis incidunt ex. Minima, sequi suscipit! Fugit architecto aut cupiditate voluptatum quisquam dolorum cum labore reprehenderit facere alias natus, nobis obcaecati ipsum adipisci rerum nihil provident dolores possimus minus ea quae. Minus molestias ipsa, expedita nesciunt ut nisi doloribus labore esse? Provident neque, eaque itaque temporibus in dolores animi corrupti expedita vel hic quibusdam illo quae commodi at nulla recusandae, necessitatibus eius tenetur magnam perspiciatis optio sed ipsam perferendis! Fuga doloribus exercitationem nisi eum quos tempora error nemo sit magnam saepe, a obcaecati mollitia illum ex distinctio iure architecto tenetur quis corporis praesentium asperiores? Eius architecto, sapiente nisi pariatur excepturi nostrum alias dolores inventore nobis.
    </div>
  )
}
